#version: "3"

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      # - "${XDEBUG_PORT}:${XDEBUG_PORT}"
#      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    depends_on:
      - database
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:rw
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${PHP_FPM}:/usr/local/etc/php-fpm.d/www.conf
#      - ${SSL_DIR}:/etc/apache2/ssl/
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${XDEBUG_LOG_DIR}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
#      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
  #   links:
  #     - database
  #   environment:
  #     PMA_HOST: database
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     UPLOAD_LIMIT: ${UPLOAD_LIMIT}
  #     MEMORY_LIMIT: ${MEMORY_LIMIT}
  #   ports:
  #     - "${HOST_MACHINE_PMA_PORT}:80"
  #     - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
  #   volumes:
  #     - /sessions
  #     - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini